### ISSUE TITLE
fopen mobilenet_ssd_voc_ncnn.param failed

### ISSUE THREAD

**Issue by laker-sprus** [rocking5566/SSD-MobileNet-ncnn#2]
Thanks for your excellent job.
After compile, error occurs:

/build_ubuntu/ssd_mobilenet 
fopen mobilenet_ssd_voc_ncnn.param failed
fopen mobilenet_ssd_voc_ncnn.bin failed
find_blob_index_by_name data failed
find_blob_index_by_name detection_out failed
time = 26.2868 ms, FPS = 38.0419, Average time = 26.2868, Average FPS = 38.0419
find_blob_index_by_name data failed

How can I fix it?
Hope your reply

**Comment by laker-sprus** [comment]
Already fixed.

**Comment by wangtong198** [comment]
I encountered the same problem, can you tell how you fixed ?
